### ISSUE TITLE
can  support kafka cluster?

### ISSUE THREAD

**Issue by 601950157** [PearceDuan/emqx-kafka-bridge#1]

**Comment by PearceDuan** [comment]
@601950157 Not yet, but seems easy to implement it; maybe you can contribute a PR

![erl-kafka](https://user-images.githubusercontent.com/15101426/123387464-63d5d400-d5ca-11eb-9c26-4f5962c7df39.png)
just change the kafkaEndpoints from one to multiple

[here is ref for erlang kafka client](https://github.com/kafka4beam/brod#quick-demo)
